version: "3.1"
services:
  postgres:
    image: postgres:11.6-alpine
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: docker
      POSTGRES_PASSWORD: docker
      POSTGRES_DB: docker
    volumes:
      - ./src/fixtures:/docker-entrypoint-initdb.d
## Google cloud build network,
# networks:
#   default:
#     external:
#       name: cloudbuild
